blueprint:
  name: Notification Blueprint
  description: Sends fixed notifications.
  domain: automation
  input:
    washer_sensor:
      name: notification sensor
      description: Entity ID
      selector:
        entity:
          domain: sensor
    message_title:
      name: Notification Title
      description: Title of the notification message.
      
    message_body:
      name: Notification Message
      description: Body of the notification message.
      

defaults: {}

trigger_type:
  name: Trigger Type
  description: Type of trigger to use for this automation.
  selector:
    select:
      options:
        - numeric_state
        - state
trigger_from:
  name: Trigger From State
  description: Initial state for the state trigger (only used if trigger type is state).
  default: ''
trigger_to:
  name: Trigger To State
  description: Target state for the state trigger (only used if trigger type is state).
  default: ''
trigger_below:
  name: Numeric Below Value
  description: Value below which the numeric_state trigger activates (only used if trigger type is numeric_state).
  default: 1

condition:
  - condition: template
    value_template: "{{ trigger.from_state.state not in ['unknown', 'unavailable'] }}"

action:
  - parallel:
      - service: notify.mobile_app_jia
        data:
          message: !input message_body
          title: !input message_title
      - service: notify.mobile_app_xujie_de_iphone
        data:
          message: !input message_body
          title: !input message_title
      - service: notify.alexa_media_jia_s_echo_dot
        data:
          message: !input message_body
          title: !input message_title
      - service: notify.alexa_media_kitchen_alexa
        data:
          message: !input message_body
          title: !input message_title
      - service: notify.alexa_media_living_room_alexa
        data:
          message: !input message_body
          title: !input message_title
      - service: notify.alexa_media_bedroom_alexa
        data:
          message: !input message_body
          title: !input message_title

mode: single

